name: Cassandra Container Test

on: push

jobs:
  run-cassandra:
    runs-on: ubuntu-latest
    container: cassandra:4.1
    steps:
      - name: Mostrar versiÃ³n de Cassandra
        run: cassandra -v

      - name: Mostrar mensaje de prueba
        run: echo "Hola desde el contenedor de Cassandra"

      - name: Listar archivos de configuraciÃ³n
        run: ls /etc/cassandra